version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - aws cloudformation package --template-file pdf-to-text.yaml --s3-bucket pdftotxt-artifacts --output-template-file pdf-to-text-output.yaml

artifacts:
  files:
    - pdf-to-text.yaml
    - pdf-to-text-output.yaml