AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: to install a Lambda function to convert pdf to text.
Resources:
  pdftotextstack:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: pdf-to-text.lambda_handler
      Runtime: python3.7
      CodeUri: .
      Description: ''
      MemorySize: 512
      Timeout: 900
      Role: 'arn:aws:iam::506160996768:role/lamda_s3_role'
      Environment:
        Variables:
          TARGET_BUCKET: pdftotxt-inter
      Layers:
        - 'arn:aws:lambda:us-east-1:506160996768:layer:tika-layer:1'
